version: '3'

services:
    nodejs-app:
        build:
          context: .
        container_name: nodejsserver
        hostname: nodejsserver
        ports:
            - "80:80" 
        networks:
            - example-net

        depends_on:
            - localhost
    localhost:
        container_name: localhost
        image: localhost
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017" 
        networks:
            - example-net 
    nginx:
        build:
          context: ./nginx
        container_name: nginx
        hostname: nginx
        ports:
            - "80:80" 
        depends_on:
            - nodejs-app
        networks:
            - example-net

networks:
  example-net:
    external: true
